WaE: initialize m_visitedParts in the member initialization list
 VSDXParser.cpp:51:1: error: 'libvisio::VSDXParser::m_visitedParts' should be initialized in the member initialization list [-Werror=effc++]

since:

commit ec5dc2dcbb97006cd1d2dbbee608934b08c33b04
Date:   Fri May 22 09:49:02 2026 +0000

    avoid infinite depth page/master relationships parse

Change-Id: I2f11d7aa13b11c67ed3362521bbad08f2b1c2e99
Reviewed-on: https://gerrit.libreoffice.org/c/libvisio/+/211256
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>